#!/usr/bin/env python
# -*- coding: UTF-8 -*-
import threading, time, serial
#from tkinter import *
import tkinter as tk
from tkinter import ttk
import serial.tools.list_ports
#标题
app = tk.Tk()
app.title("串口助手")
app.geometry('470x320+400+100')     #默认窗体大小

#bulidButtonClick按键点击事件
def checkButtonClick():
    port_list = list(serial.tools.list_ports.comports())
    lenport_list = len(port_list)
    if lenport_list <= 0:
        inputLogWindow.insert("The Serial port can't find!")
    else:
        for i in range(0, len(port_list)):
            inputLogWindow.insert(tk.END, port_list[i])
            inputLogWindow.insert(tk.END, '\n')
            inputLogWindow.see(tk.END)
    #print(port_list)
#按键生成
frameButton = ttk.Frame(app)
frameButton.pack(fill=tk.X)
checkButton = tk.Button(frameButton, text = "生成!", width = 15, command = checkButtonClick)
checkButton.pack(fill=tk.BOTH, side=tk.LEFT,padx = 11, pady = 11)

#ClearButtomClick清除按键点击事件
def ClearButtomClick():
    inputLogWindow.delete(0.0,tk.END)
#Log窗口
frameLogWindow = tk.Frame(app)
frameLogWindow.pack(fill=tk.BOTH, expand = 1)
tk.Label(frameLogWindow, text = "测试信息打印窗口:", bg = "gray", fg = "white", width = 15).pack(fill=tk.X)
clearButton = tk.Button(frameLogWindow, text = "清除打印信息!", command = ClearButtomClick).pack(fill=tk.X)
inputLogWindow = tk.Text(frameLogWindow)
inputLogWindow.insert('1.0',"测试信息打印窗口\n")
inputLogWindow.pack(fill=tk.BOTH,side=tk.LEFT,expand = 1)

# ======================
# Start GUI
# ======================
app.mainloop()